# <Center>02</center>
## <Center>(Numpy, Pandas, Matplotlib)</center>

# 01. Numpy

### Introduction to NUMPY
### What is NumPy?
- NumPy is a Python library used for working with arrays.
- It also has functions for working in domain of linear algebra, fourier transform, and matrices.
- NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
- NumPy stands for Numerical Python.

### Why Use NumPy?
- In Python we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
- Arrays are very frequently used in data science, where speed and resources are very important.

### Why is NumPy Faster Than Lists?

- NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
- This behavior is called locality of reference in computer science.
- This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.



### Example 01
- Take 2 lists and multiply both you’ll see that error occurs repeat the process but by  coverting them toarray by numpy.array()

In [1]:
l1 = [1,2,3]
l2 = [4,5,6]

l1*l2

TypeError: can't multiply sequence by non-int of type 'list'

- Now, by using numpy

In [4]:
import numpy as np

l1 = [1,2,3]
l2 = [4,5,6]

A1 = np.array(l1)
A2 = np.array(l2)

print(f"{A1} * {A2} = {A1*A2}")

[1 2 3] * [4 5 6] = [ 4 10 18]


### Example 02

- Demonstrate the use of numpy.dtype and numpy.shape() functions

In [5]:
import numpy as np

l1 = [1,2,3]
l2 = [4,5,6]

A1 = np.array(l1)
A2 = np.array(l2)

A = A1*A2

print(f"{A1} * {A2} = {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

[1 2 3] * [4 5 6] = [ 4 10 18]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int32
The dimension of an array: (3,)


### Example 03

- The size of an array created with numpy.array() is int32 convert it to int 8

In [6]:
import numpy as np

l1 = [1,2,3]
l2 = [4,5,6]

A1 = np.array(l1, np.int8)
A2 = np.array(l2, np.int8)

A = A1*A2

print(f"{A1} * {A2} = {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

[1 2 3] * [4 5 6] = [ 4 10 18]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int8
The dimension of an array: (3,)


### Example 04

- Demonstrate the use of numpy.size() functions

In [8]:
import numpy as np

l1 = [1,2,3]
l2 = [4,5,6]

A1 = np.array(l1, np.int8)
A2 = np.array(l2, np.int8)

A = A1*A2

print(f"{A1} * {A2} = {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array


[1 2 3] * [4 5 6] = [ 4 10 18]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int8
The dimension of an array: (3,)
The size of an array: 3


### Example 05

- Create a 2D array using numpy.array()

In [13]:
import numpy as np

l1 = [1,2,3]
l2 = [4,5,6]

A = np.array((l1, l2))
print(f" The 2D array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array


 The 2D array is : 
 [[1 2 3]
 [4 5 6]]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int32
The dimension of an array: (2, 3)
The size of an array: 6


### Example 06
- Create a 1 D array by passing a list

In [15]:
A = np.array(([1,2,3,4,5]))
print(f" The 1D array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array


 The 1D array is : 
 [1 2 3 4 5]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int32
The dimension of an array: (5,)
The size of an array: 5


### Example 07
- Create a 2 D array by passing lists

In [18]:
import numpy as np

A = np.array(([1,2,3,4,5], [2,3,4,5,6]))
print(f" The 2D array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array


 The 2D array is : 
 [[1 2 3 4 5]
 [2 3 4 5 6]]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int32
The dimension of an array: (2, 5)
The size of an array: 10


### Example 08
- Create 4 x 4 Matrix

In [21]:
import numpy as np

r1 = [1,2,3,4]
r2 = [3,6,3,4]
r3 = [1,2,9,4]
r4 = [1,4,5,4]

A = np.array((r1,r2,r3,r4))
print(f" The array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array


 The array is : 
 [[1 2 3 4]
 [3 6 3 4]
 [1 2 9 4]
 [1 4 5 4]]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int32
The dimension of an array: (4, 4)
The size of an array: 16


### Example 09
- Replace 2nd row 3rd element of above 4x4 matrix with 10

In [23]:
import numpy as np

r1 = [1,2,3,4]
r2 = [3,6,3,4]
r3 = [1,2,9,4]
r4 = [1,4,5,4]

A = np.array((r1,r2,r3,r4))
print(f" The original array is : \n {A}")

A[1,2] = 10
print(f" The array after replacing : \n {A}")



 The original array is : 
 [[1 2 3 4]
 [3 6 3 4]
 [1 2 9 4]
 [1 4 5 4]]
 The array after replacing : 
 [[ 1  2  3  4]
 [ 3  6 10  4]
 [ 1  2  9  4]
 [ 1  4  5  4]]


### Example 10
- Create a 5 x 5 matrix of all zeros by setting values of both rows and column

In [24]:
import numpy as np

A = np.zeros([5,5])
print(f" The array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array


 The array is : 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: float64
The dimension of an array: (5, 5)
The size of an array: 25


### Example 11
- Create a 5 x 5 matrix of all zeros by passing only 1 argument

In [29]:
import numpy as np

A = np.zeros([5])
print(f" The array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array


 The array is : 
 [0. 0. 0. 0. 0.]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: float64
The dimension of an array: (5,)
The size of an array: 5


### Example 12
- Create an array from 1 to 100 by numpy.arrange()

In [32]:
import numpy as np

A = np.arange(1,100)
print(f" The array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array


 The array is : 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int32
The dimension of an array: (99,)
The size of an array: 99


### Example 13
- Create an array from 1 to 100 by numpy.arrange() with a stepsize of 10

In [33]:
import numpy as np

A = np.arange(1,100,10)
print(f" The array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array


 The array is : 
 [ 1 11 21 31 41 51 61 71 81 91]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int32
The dimension of an array: (10,)
The size of an array: 10


### Example 14
- Create an array of 100 elements ranging from 2 to 3

In [34]:
import numpy as np

A = np.linspace(2,3,100)
print(f" The array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array


 The array is : 
 [2.         2.01010101 2.02020202 2.03030303 2.04040404 2.05050505
 2.06060606 2.07070707 2.08080808 2.09090909 2.1010101  2.11111111
 2.12121212 2.13131313 2.14141414 2.15151515 2.16161616 2.17171717
 2.18181818 2.19191919 2.2020202  2.21212121 2.22222222 2.23232323
 2.24242424 2.25252525 2.26262626 2.27272727 2.28282828 2.29292929
 2.3030303  2.31313131 2.32323232 2.33333333 2.34343434 2.35353535
 2.36363636 2.37373737 2.38383838 2.39393939 2.4040404  2.41414141
 2.42424242 2.43434343 2.44444444 2.45454545 2.46464646 2.47474747
 2.48484848 2.49494949 2.50505051 2.51515152 2.52525253 2.53535354
 2.54545455 2.55555556 2.56565657 2.57575758 2.58585859 2.5959596
 2.60606061 2.61616162 2.62626263 2.63636364 2.64646465 2.65656566
 2.66666667 2.67676768 2.68686869 2.6969697  2.70707071 2.71717172
 2.72727273 2.73737374 2.74747475 2.75757576 2.76767677 2.77777778
 2.78787879 2.7979798  2.80808081 2.81818182 2.82828283 2.83838384
 2.84848485 2.85858586 2.86868687 2.87878788 

### Example 15
- Create identity matrix

In [35]:
import numpy as np

A = np.identity(5)
print(f" The array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array


 The array is : 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: float64
The dimension of an array: (5, 5)
The size of an array: 25


### Example 16
- Create a 4 x 4 matrix and find the sum of all columns

In [37]:
import numpy as np

r1 = [1,2,3,4]
r2 = [3,6,3,4]
r3 = [1,2,9,4]
r4 = [1,4,5,4]

A = np.array((r1,r2,r3,r4))
print(f" The Matrix is : \n {A}")

print(f" The row wise sum is : {A.sum(axis=1)}")
print(f" The column wise sum is : {A.sum(axis=0)}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array


 The Matrix is : 
 [[1 2 3 4]
 [3 6 3 4]
 [1 2 9 4]
 [1 4 5 4]]
 The row wise sum is : [10 16 16 14]
 The column wise sum is : [ 6 14 20 16]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int32
The dimension of an array: (4, 4)
The size of an array: 16


### Example 17
- Find the transpose of a Matrix

In [38]:
import numpy as np

r1 = [1,2,3,4]
r2 = [3,6,3,4]
r3 = [1,2,9,4]
r4 = [1,4,5,4]

A = np.array((r1,r2,r3,r4))
print(f" The Matrix is : \n {A}")

print(f" The transpose is : \n {A.T}")

 The Matrix is : 
 [[1 2 3 4]
 [3 6 3 4]
 [1 2 9 4]
 [1 4 5 4]]
 The transpose is : 
 [[1 3 1 1]
 [2 6 2 4]
 [3 3 9 5]
 [4 4 4 4]]


### Example 18
- Use reshape command to convrt 4 x 4 matrix to 8 x 2

In [41]:
import numpy as np

r1 = [1,2,3,4]
r2 = [3,6,3,4]
r3 = [1,2,9,4]
r4 = [1,4,5,4]

A = np.array((r1,r2,r3,r4))
print(f" The 4x4 Matrix is : \n {A}")

print(f" The 8x2 matrix: \n {A.reshape(8,2)}")

 The 4x4 Matrix is : 
 [[1 2 3 4]
 [3 6 3 4]
 [1 2 9 4]
 [1 4 5 4]]
 The 8x2 matrix: 
 [[1 2]
 [3 4]
 [3 6]
 [3 4]
 [1 2]
 [9 4]
 [1 4]
 [5 4]]


### Example 19
- Demonstrate the use of numpy.ravel()

In [43]:
import numpy as np

r1 = [1,2,3,4]
r2 = [3,6,3,4]
r3 = [1,2,9,4]
r4 = [1,4,5,4]

A = np.array((r1,r2,r3,r4))
print(f" The 4x4 Matrix is : \n {A}")

print(f" The 1D array from above matrix using ravel: \n {A.ravel()}")


 The 4x4 Matrix is : 
 [[1 2 3 4]
 [3 6 3 4]
 [1 2 9 4]
 [1 4 5 4]]
 The 1D array from above matrix using ravel: 
 [1 2 3 4 3 6 3 4 1 2 9 4 1 4 5 4]


### Example 20
- Demonstrate the use of argmax, argmin,argsort

In [44]:
import numpy as np

a = [1, 16, 31, 4]

A = np.array(a)
print(f"The original array: {A}")

print(f"The index of maximum value in array is: {A.argmax()}")
print(f"The index of minimum value in array is: {A.argmin()}")
print(f"Sorted Indexes: {A.argsort()}")

The original array: [ 1 16 31  4]
The index of maximum value in array is: 2
The index of minimum value in array is: 0
Sorted Indexes: [0 3 1 2]


### Example 21
- Demostrate the use of numpy.full(),vstack(),hstack(),column_stack()

In [3]:
import numpy as np

f1=np.full((2,2),5)
f1

array([[5, 5],
       [5, 5]])

In [4]:
f2 = np.full((2,2), 3)
f2

array([[3, 3],
       [3, 3]])

In [6]:
a = np.vstack([f1, f2])
a

array([[5, 5],
       [5, 5],
       [3, 3],
       [3, 3]])

In [7]:
b = np.hstack([f1, f2])
b

array([[5, 5, 3, 3],
       [5, 5, 3, 3]])

In [8]:
a = np.column_stack([f1, f2])
a

array([[5, 5, 3, 3],
       [5, 5, 3, 3]])

### Example 22
- Save and load a matrix in the memory 

In [9]:
import numpy as np

a = np.full((2,3), 5)
a

array([[5, 5, 5],
       [5, 5, 5]])

In [10]:
np.save("untitled.npy", a)

In [11]:
savedMatrix = np.load('untitled.npy')
savedMatrix

array([[5, 5, 5],
       [5, 5, 5]])

### Example 23
- Demonstrate the use of numoy.dot() and compare it with simple multiplication

In [12]:
import numpy as np

f1=np. full((2,2),5)
print("\nf1 = \n",f1)

f2=np.full((2,2), 3)
print("\nf2 = \n", f2)

print("point to point multiplication = ",f1*f2)

print("point to point multiplication = ", np.dot(f1,f2))


f1 = 
 [[5 5]
 [5 5]]

f2 = 
 [[3 3]
 [3 3]]
point to point multiplication =  [[15 15]
 [15 15]]
point to point multiplication =  [[30 30]
 [30 30]]


# 02. Pandas

### Example 01
- ``Create a Dictionary and convert them into data frames also check its datatype``

In [14]:
#create a dictionary

StuDict={"Name": ["Aqsa","Esha", "Ayesha", "Ayra", "Arfa", "Afsa", "Abdul", "Saadia", "Abu Bakar","Atif"],
"ID": ["SID-1","SID-2", "SID-3", "SID-4", "SID-5","SID-6", "SID-7", "SID-8", "SID-9","SID-10"],
"Rol1_no": [1,2,3,4,5,6,7,8,9,10],
"Semester" : [7,7,7,7,6,6,6,5,8,8]}

StuDict

{'Name': ['Aqsa',
  'Esha',
  'Ayesha',
  'Ayra',
  'Arfa',
  'Afsa',
  'Abdul',
  'Saadia',
  'Abu Bakar',
  'Atif'],
 'ID': ['SID-1',
  'SID-2',
  'SID-3',
  'SID-4',
  'SID-5',
  'SID-6',
  'SID-7',
  'SID-8',
  'SID-9',
  'SID-10'],
 'Rol1_no': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 'Semester': [7, 7, 7, 7, 6, 6, 6, 5, 8, 8]}

In [16]:
#convert into data frames

import pandas as pd

data=pd.DataFrame (StuDict)

print(data)

print("\n\nThe data type of above given syntax is :",type (data))


        Name      ID  Rol1_no  Semester
0       Aqsa   SID-1        1         7
1       Esha   SID-2        2         7
2     Ayesha   SID-3        3         7
3       Ayra   SID-4        4         7
4       Arfa   SID-5        5         6
5       Afsa   SID-6        6         6
6      Abdul   SID-7        7         6
7     Saadia   SID-8        8         5
8  Abu Bakar   SID-9        9         8
9       Atif  SID-10       10         8


The data type of above given syntax is : <class 'pandas.core.frame.DataFrame'>


### Example 02
- `Demonstrate the use of describe function for a data frame`

In [21]:
print(data.describe())

        Rol1_no   Semester
count  10.00000  10.000000
mean    5.50000   6.700000
std     3.02765   0.948683
min     1.00000   5.000000
25%     3.25000   6.000000
50%     5.50000   7.000000
75%     7.75000   7.000000
max    10.00000   8.000000


### Example 03
- `Demonstrate the use of head function for a data frame`

In [22]:
print(data.head())

     Name     ID  Rol1_no  Semester
0    Aqsa  SID-1        1         7
1    Esha  SID-2        2         7
2  Ayesha  SID-3        3         7
3    Ayra  SID-4        4         7
4    Arfa  SID-5        5         6


### Example 04
- `Demonstrate the use of tail function for a data frame`

In [23]:
print(data.tail())

        Name      ID  Rol1_no  Semester
5       Afsa   SID-6        6         6
6      Abdul   SID-7        7         6
7     Saadia   SID-8        8         5
8  Abu Bakar   SID-9        9         8
9       Atif  SID-10       10         8


### Example 05
- `Demonstrate the use of info function for a data frame`

In [24]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Name      10 non-null     object
 1   ID        10 non-null     object
 2   Rol1_no   10 non-null     int64 
 3   Semester  10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 448.0+ bytes
None


### Example 06
- `Convert the data frame in a variable to CSV file`

In [25]:
data.to_csv('student.csv')

### Example 07
- `Remove the indexes from the csv file`

In [27]:
data.to_csv('Without_index.csv', index=False)

### Example 08
- `Read from csv file`

In [28]:
df = pd.read_csv('student.csv')
df

Unnamed: 0       Name      ID  Rol1_no  Semester
0           0       Aqsa   SID-1        1         7
1           1       Esha   SID-2        2         7
2           2     Ayesha   SID-3        3         7
3           3       Ayra   SID-4        4         7
4           4       Arfa   SID-5        5         6
5           5       Afsa   SID-6        6         6
6           6      Abdul   SID-7        7         6
7           7     Saadia   SID-8        8         5
8           8  Abu Bakar   SID-9        9         8
9           9       Atif  SID-10       10         8

### Example 09
- `Use describe,head,tail and info function for CSV file`

In [1]:
import pandas as pd
df = pd.read_csv('student.csv')

print(f"Describe Function \n {df.describe()}, \n head Function \n {df.head()} \n tail Function \n {df.tail()}")
print(f"\n info Function \n {df.info()}")

Describe Function 
        Unnamed: 0   Rol1_no   Semester
count    10.00000  10.00000  10.000000
mean      4.50000   5.50000   6.700000
std       3.02765   3.02765   0.948683
min       0.00000   1.00000   5.000000
25%       2.25000   3.25000   6.000000
50%       4.50000   5.50000   7.000000
75%       6.75000   7.75000   7.000000
max       9.00000  10.00000   8.000000, 
 head Function 
    Unnamed: 0    Name     ID  Rol1_no  Semester
0           0    Aqsa  SID-1        1         7
1           1    Esha  SID-2        2         7
2           2  Ayesha  SID-3        3         7
3           3    Ayra  SID-4        4         7
4           4    Arfa  SID-5        5         6 
 tail Function 
    Unnamed: 0       Name      ID  Rol1_no  Semester
5           5       Afsa   SID-6        6         6
6           6      Abdul   SID-7        7         6
7           7     Saadia   SID-8        8         5
8           8  Abu Bakar   SID-9        9         8
9           9       Atif  SID-10       10   

### Example 10
- `Access a column by its name`

In [2]:
import pandas as pd

df['Name']

0         Aqsa
1         Esha
2       Ayesha
3         Ayra
4         Arfa
5         Afsa
6        Abdul
7       Saadia
8    Abu Bakar
9         Atif
Name: Name, dtype: object

### Example 11
- `Access the 1st element of a column`

In [3]:

df['Name'][0]

'Aqsa'

### Example 12
- `Update the value in the column`

In [4]:
df['Name'][0] = 'Saddam'
df

C:\Users\hp\AppData\Local\Temp\ipykernel_17156\2832195598.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Name'][0] = 'Saddam'


Unnamed: 0       Name      ID  Rol1_no  Semester
0           0     Saddam   SID-1        1         7
1           1       Esha   SID-2        2         7
2           2     Ayesha   SID-3        3         7
3           3       Ayra   SID-4        4         7
4           4       Arfa   SID-5        5         6
5           5       Afsa   SID-6        6         6
6           6      Abdul   SID-7        7         6
7           7     Saadia   SID-8        8         5
8           8  Abu Bakar   SID-9        9         8
9           9       Atif  SID-10       10         8

### Example 13
- `Find the columns and indexes in a data frame`

In [5]:
df.columns

Index(['Unnamed: 0', 'Name', 'ID', 'Rol1_no', 'Semester'], dtype='object')

In [6]:
df.index

RangeIndex(start=0, stop=10, step=1)

# 03. Matplotlib